# Generated by Django 5.0.6 on 2024-07-09 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StockList',
            new_name='Stock',
        ),
    ]
