# Generated by Django 5.0.6 on 2024-07-09 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_stocklist_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='company_symbol',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
